languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Johakim's Portfolio"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "My awesome portfolio website"

[params.author]
name = "Johakim Fontaine Barboza"
image = "img/face.png"
headline = "Junior Software Developer"
bio = "Montreal based junior dev with a passion in AI and Audio Programming"
links = [
  { email = "mailto:johakimfb@protonmail.com" },
  { github = "https://github.com/kunyro" },
  { gitlab = "https://gitlab.com/johakim" },
  { linkedin = "https://linkedin.com/in/johakim" },
  ]